apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-app-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-app
  targetCPUUtilizationPercentage: 30