pipeline{
    agent any

    parameters{
        string(name: 'NAME', defaultValue: 'springtest')
    }

    stages{
        stage('SCM'){
            steps{
                sh "echo SCM..."
                checkout scm
            }
        }

        stage('Springboot build'){
            steps{
                dir('backend'){
                    sh '''
                        echo 'Springboot build...'
                        mkdir -p src/main/resources
                        cp /var/jenkins_home/env/application.yml ./src/main/resources/application.yml
                        chmod +x gradlew
                        ./gradlew clean build
                    '''
                }
            }
        }

        stage('Send JAR File to Deploy Server'){
            steps{
                dir('backend'){
                    sh '''
                        echo 'Send JAR File to Deploy Server...'
                        scp -i /var/jenkins_home/.ssh/id_rsa/id_rsa ./build/libs/algonote-0.0.1-SNAPSHOT.jar ubuntu@k10b203.p.ssafy.io:/home/ubuntu/spring/algonote-0.0.1-SNAPSHOT.jar
                        scp -i /var/jenkins_home/.ssh/id_rsa/id_rsa ./Dockerfile ubuntu@k10b203.p.ssafy.io:/home/ubuntu/spring/Dockerfile
                        scp -i /var/jenkins_home/.ssh/id_rsa/id_rsa ./init.sh ubuntu@k10b203.p.ssafy.io:/home/ubuntu/spring/init.sh
                    '''
                }
            }
        }

        stage('Docker build'){
            steps{
                dir('backend'){
                    sh 'ssh -i /var/jenkins_home/.ssh/id_rsa/id_rsa ubuntu@k10b203.p.ssafy.io "cd /home/ubuntu/spring && sh init.sh"  ' 
                }
            }
        }
    }

}