pipeline{
    environment{
        repository = "tollea1234/algonote-frontend"
        DOCKERHUB_CREDENTIALS = credentials('docker') // jenkins에 등록해 놓은 docker hub credentials 이름
        dockerImage = '' 
    }

    agent any

    stages{
        stage('Build docker image'){
            steps{
                dir('frontend/algonote'){
                    script{
                        dockerImage = docker.build repository + ":$BUILD_NUMBER"
                    }
                }
            }
        }
        
        stage('Login'){
          steps{
              sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin' // docker hub 로그인
          }
        }
        
        stage('Deploy our image') { 
            steps { 
                script {
                    sh 'docker push $repository:$BUILD_NUMBER' //docker push
                } 
            }
        } 
        stage('Cleaning up') { 
            steps { 
                sh "docker rmi $repository:$BUILD_NUMBER" // docker image 제거
            }
        } 

        stage('Deploy on deploy Server'){
            steps{
                sh '''
                    ssh -i /var/jenkins_home/.ssh/id_rsa ubuntu@k10b203.p.ssafy.io "docker pull tollea1234/algonote-frontend:latest"
                    ssh -i /var/jenkins_home/.ssh/id_rsa ubuntu@k10b203.p.ssafy.io "docker rm frontend-container --force"
                    ssh -i /var/jenkins_home/.ssh/id_rsa ubuntu@k10b203.p.ssafy.io "docker run -p 3000:3000 -d --name frontend-container tollea1234/algonote-frontend:latest"
                    
                '''
            }
        }
    }
}