# FROM ubuntu:20.04
FROM python:3.10.14

WORKDIR /app

RUN apt-get update && \
    apt-get install -y wget bzip2 curl git bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /miniconda && \
    rm Miniconda3-latest-Linux-x86_64.sh

ENV PATH=/miniconda/bin:$PATH

COPY environment.yaml /app/environment.yaml
RUN conda env create -f environment.yaml

# Activate the conda environment
RUN echo "conda activate torch" >> ~/.bashrc
ENV PATH=/miniconda/envs/torch/bin:$PATH

# Copy the rest of the application code
COPY . .

# Set the entry point for the container
CMD ["python", "main.py"]