import { useEffect } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import s from './main.module.scss'
import { SimpleButton } from '@/components/commons/Buttons/Button'
import Radar from '@/components/commons/Main/Radar'
import Wave from '@/components/commons/Main/Wave'
import { getCookie } from '@/utils/cookie'

const Home = () => {
  const router = useRouter()

  useEffect(() => {
    const accessToken = getCookie('access_token')
    console.log(accessToken)
    if (!accessToken) {
      router.replace('/landing') // 사용자를 '/landing' 페이지로 리다이렉트합니다.
    }
  }, [router])

  return (
    <>
      <Head>
        <title>algonote</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={s.main}>
        <div className={s.header}>
          <div className={s.headerSentence}>
            <p className={s.headerLight}>당신의 알고리즘</p>
            <p className={s.headerBold}>약점 보완</p>
            <p className={s.headerLight}>을 위한</p>
          </div>
          <div className={s.headerSentence}>
            <p className={s.headerLight}>가장 완벽한 알고리즘 오답노트,</p>
            <p className={s.headerBold}>알고노트</p>
          </div>
        </div>
        <div className={s.container}>
          <h2 className={s.title}>내 알고리즘 실력 분석</h2>
          <div className={s.analysis}>
            <div className={s.radarCont}>
              <p className={s.graphTitle}>종합점수</p>
              <div className={s.radarBox}>
                <Radar data={[]} labels={[]} />
              </div>
            </div>
            <div className={s.right}>
              <div className={s.textCont}>
                <a href="./member">상당히느긋한사람</a>
                <p>님은 알고노트에 가입한 이후로,</p>
              </div>
              <div className={s.sentenceCont}>
                <div className={s.textCont}>
                  <div className={s.numCont}>
                    <a href="./solvedproblems">24</a>
                  </div>
                  <p>개의 문제를 풀었어요</p>
                </div>
                <div className={s.textCont}>
                  <div className={s.numCont}>
                    <a href="./mynote">7</a>
                  </div>
                  <p>개의 문제에 대해</p>
                </div>
                <div className={s.textCont}>
                  <div className={s.numCont}>
                    <a href="./mynote">12</a>
                  </div>
                  <p>개의 노트를 작성했어요</p>
                </div>
              </div>
              <SimpleButton
                text="노트 작성하러 가기"
                style={{ fontWeight: '700' }}
                onClick={() => router.push('/solvedproblems')}
              />
            </div>
          </div>
        </div>

        <hr className={s.divide} />

        <div className={s.container}>
          <h2 className={s.title}>문제 추천</h2>
          <div className={s.recommendCont}>
            <div className={s.wave}>
              <Wave type="수학" score={34} />
            </div>
            <div className={s.wave}>
              <Wave type="그래프" score={75} />
            </div>
            <div className={s.wave}>
              <Wave type="자료구조" score={54} />
            </div>
            <div className={s.wave}>
              <Wave type="자료구조" score={67} />
            </div>
            <div className={s.wave}>
              <Wave type="자료구조" score={3} />
            </div>
            <div className={s.wave}>
              <Wave type="자료구조" score={14} />
            </div>
          </div>
          <SimpleButton
            text="추천 문제 보러가기"
            style={{ fontWeight: '700' }}
            onClick={() => router.push('/recommend')}
          />
        </div>
      </main>
    </>
  )
}

export default Home
